### ISSUE TITLE
Generate bindings to fetch-API

### ISSUE THREAD

**Issue by mekeor** [stefan-hoeck/idris2-webidl#20]
In https://github.com/stefan-hoeck/idris2-dom/issues/13#issuecomment-1340346772, @stefan-hoeck stated:

>  idris2-webidl does not generate those bindings, because I have not yet added the corresponding webidl files to it.

I request to add those webidl-files, so that idris2-webidl will generate bindings to the fetch-API.

**Comment by mekeor** [comment]
@stefan-hoeck, I don't exactly understand why the bindings are not generated yet. Aren't the webidl-files for the fetch-standard already present here?: https://github.com/stefan-hoeck/idris2-webidl/blob/main/idl/fetch.webidl

**Comment by stefan-hoeck** [comment]
Yes, they are. I'll try and figure out what's going on here.

**Comment by stefan-hoeck** [comment]
Looks like the following part is missing from `html.webidl`: [link](https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope-mixin). I'm currently experimenting with this locally.

**Comment by mekeor** [comment]
> Looks like the following part is missing from html.webidl: link. 
> I'm currently experimenting with this locally.

Thank you very much for investigating. I'm convinced that this 
would make a big difference for people using Idris for frontend 
development.

**Comment by stefan-hoeck** [comment]
Could you have a look at #22 and stefan-hoeck/idris2-dom#39 and give some feedback if this is what was missing?

**Comment by mekeor** [comment]
The PR to idris2-dom [introduces](https://github.com/stefan-hoeck/idris2-dom/blob/98dd0fbf21e17e3b305b60c0d2f40627cca033c0/src/Web/Raw/Html.idr#L9128-L9147) `fetch` and `fetch'` which is what was missing. Unfortunately, I don't have time to test the changes. But it looks good to me!

**Comment by stefan-hoeck** [comment]
OK, I'll merge this then, and if something is still missing, you can open another issue. Sorry this took so long.

**Comment by mekeor** [comment]
No problem :)

**Comment by stefan-hoeck** [comment]
I'm going to close this, since this has been added. Feel free to reopen if this is still an issue.
